Charview, Button key labels, bugfix
Liadri/Corruption-of-Champions pull request #6
Opened 2018-04-03 06:13 UTC by aimozg

2018-04-04 23:01 UTC, Oxdeception requested changes
Changes made break the key binds. There also needs to be the option to toggle the key display.

2018-04-04 23:01 UTC, Oxdeception commented on classes/classes/ControlBindings.as
> +							executeButtonClick(i);
This causes all of the keys to call button 15.

2018-04-04 23:48 UTC, aimozg commented
Fixed

2018-04-05 01:04 UTC, Oxdeception approved these changes

2018-04-05 01:05 UTC, merged